Repository fluxninja/grafana, pull requests merged in 2022-11, with the labels that each got.

#30 removed extra components and added lazy loading
  package.json
  public/app/fn-app/fn-app-provider.tsx
  public/app/fn-app/fn-dashboard-page/fn-dashboard.tsx
  yarn.lock
Labels: size/M

#31 render MFE with portal
  package.json
  public/app/core/reducers/fn-slice.ts
  public/app/features/dashboard/containers/DashboardPage.tsx
  public/app/fn-app/filter-constants/constants.ts
  public/app/fn-app/filter-constants/index.ts
  public/app/fn-app/filter-constants/types.ts
  public/app/fn-app/fn-app-provider.tsx
  public/app/fn-app/fn-dashboard-page/fn-dashboard.tsx
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
  public/app/fn-app/types.ts
  public/app/fn-app/utils.tsx
  yarn.lock
Labels: size/L

#32 Revert "render MFE with portal"
  package.json
  public/app/core/reducers/fn-slice.ts
  public/app/features/dashboard/containers/DashboardPage.tsx
  public/app/fn-app/filter-constants/constants.ts
  public/app/fn-app/filter-constants/index.ts
  public/app/fn-app/filter-constants/types.ts
  public/app/fn-app/fn-app-provider.tsx
  public/app/fn-app/fn-dashboard-page/fn-dashboard.tsx
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
  public/app/fn-app/types.ts
  public/app/fn-app/utils.tsx
  yarn.lock
Labels: size/L

#33 Fixed command to update environment on changes
  .circleci/scripts/update_environment.sh
Labels: size/XS

#34 Render with portal pass query params
  package.json
  public/app/core/reducers/fn-slice.ts
  public/app/features/dashboard/containers/DashboardPage.tsx
  public/app/fn-app/filter-constants/constants.ts
  public/app/fn-app/filter-constants/index.ts
  public/app/fn-app/filter-constants/types.ts
  public/app/fn-app/fn-app-provider.tsx
  public/app/fn-app/fn-dashboard-page/fn-dashboard.tsx
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
  public/app/fn-app/types.ts
  public/app/fn-app/utils.tsx
  yarn.lock
Labels: size/L
