Repository fluxninja/grafana, pull requests merged in 2022-09, with the labels that each got.

#6 Fix variable queries
  pkg/tsdb/druid/druid.go
Labels: size/S

#7 GH-6079 Replace slug with panel title
  public/app/features/dashboard/dashgrid/PanelChrome.tsx
Labels: size/XS

#9 GH-6169 catch errors, improve types, add FN_README
  FN_README.md
  packages/grafana-runtime/src/services/LocationService.ts
  packages/grafana-ui/src/components/ToolbarButton/ToolbarButton.tsx
  public/app/core/components/Page/usePageTitle.ts
  public/app/core/reducers/fn-slice.ts
  public/app/core/reducers/index.ts
  public/app/features/alerting/unified/mocks.ts
  public/app/features/dashboard/components/DashNav/DashNav.tsx
  public/app/features/dashboard/components/SubMenu/SubMenu.tsx
  public/app/features/dashboard/components/SubMenu/SubMenuItems.tsx
  public/app/features/dashboard/containers/DashboardPage.tsx
  public/app/features/dashboard/dashgrid/PanelChrome.tsx
  public/app/features/dashboard/dashgrid/liveTimer.ts
  public/app/features/variables/pickers/PickerRenderer.tsx
  public/app/fn-app/create-mfe.ts
  public/app/fn-app/fn-app-provider.tsx
  public/app/fn-app/fn-dashboard-page/fn-dashboard.tsx
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
  public/app/fn-app/types.ts
  public/app/fn_app.ts
  public/app/fn_dashboard.ts
  public/app/store/configureStore.ts
  public/app/types/dashboard.ts
  public/test/redux-rtl.tsx
Labels: size/XL

#10 Gh 6196 catch errors thrown by grafana
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
Labels: size/S

#11 GH-6169 catch errors
  public/app/fn-app/create-mfe.ts
Labels: size/XS

#12 GH-6381 Update theme
  public/app/fn-app/create-mfe.ts
Labels: size/S
