Repository fluxninja/grafana, pull requests merged in 2022-10, with the labels that each got.

#13 GH-6578 Use fn loader
  public/app/features/dashboard/containers/DashboardPage.tsx
  public/app/fn-app/fn-dashboard-page/fn-dashboard.tsx
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
Labels: size/M

#14 Add .opsninja.yaml with repository tooling configuration
  .opsninja.yaml
Labels: size/XS

#16 GH-6542 Implement logger
  public/app/fn-app/create-mfe.ts
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
  public/app/fn_logger.ts
Labels: size/M

#17 Add missing commits
  package.json
  pkg/tsdb/druid/druid.go
  public/app/features/dashboard/containers/DashboardPage.tsx
  public/app/fn-app/fn-dashboard-page/fn-dashboard.tsx
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
  yarn.lock
Labels: size/L

#18 Improve error handling
  pkg/tsdb/druid/druid.go
Labels: size/S

#20 Typed response
  go.mod
  pkg/tsdb/druid/column_type.go
  pkg/tsdb/druid/druid.go
  pkg/tsdb/druid/result/common.go
  pkg/tsdb/druid/result/timeseries.go
  pkg/tsdb/druid/result/timeseries_test.go
  pkg/tsdb/druid/result/topn.go
  pkg/tsdb/druid/result/topn_test.go
Labels: size/XL

#21 Added release components for Grafana
  .circleci/config.yml
  .circleci/scripts/asdf_install.sh
  .circleci/scripts/manage_tools.sh
  .tool-versions
Labels: size/L

#22 Fixed errors in the release pipeline
  .circleci/scripts/manage_tools.sh
  requirements.txt
Labels: size/XS

#23 Enabled setup mode for CircleCi
  .circleci/config.yml
Labels: size/XS

#24 Update demo environment on "main" grafana merges
  .circleci/config.yml
  .circleci/scripts/update_environment.sh
Labels: size/L

#25 GH-6804 Fix bugs in theme toggling
  packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker.tsx
  packages/grafana-ui/src/components/ToolbarButton/ToolbarButton.tsx
  public/app/core/components/TimePicker/TimePickerWithHistory.tsx
  public/app/core/reducers/fn-slice.ts
  public/app/features/dashboard/containers/DashboardPage.tsx
  public/app/features/dashboard/dashgrid/PanelChrome.tsx
  public/app/features/variables/pickers/PickerRenderer.tsx
  public/app/fn-app/create-mfe.ts
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
  public/app/fn-app/types.ts
Labels: size/L

#26 GH-6804 Fix bugs in theme toggling
  public/app/core/components/TimePicker/TimePickerWithHistory.tsx
  public/app/core/reducers/fn-slice.ts
  public/app/fn-app/create-mfe.ts
Labels: size/S

#27 GH-6804 Fix bugs in theme toggling
  public/app/core/reducers/fn-slice.ts
  public/app/fn-app/create-mfe.ts
Labels: size/S

#28 GH-6804
  packages/grafana-data/src/themes/fnCreateColors.ts
  public/app/fn-app/create-mfe.ts
Labels: size/L

#29 6595 use grafana theme
  packages/grafana-data/src/themes/fnCreateColors.ts
  packages/grafana-data/src/themes/fnPalette.ts
  public/app/core/components/Page/usePageTitle.ts
  public/app/core/components/TimePicker/TimePickerWithHistory.tsx
  public/app/core/reducers/fn-slice.ts
  public/app/features/variables/pickers/PickerRenderer.tsx
  public/app/fn-app/create-mfe.ts
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
  public/app/fn-app/types.ts
Labels: size/L
