Repository fluxninja/grafana, pull requests merged in 2022-12, with the labels that each got.

#35 fix
  public/app/fn-app/fn-dashboard-page/fn-dashboard.tsx
Labels: size/XS

#36 add sankey charts plugin to grafana
  public/app/features/plugins/built_in_plugins.ts
  public/app/plugins/panel/netsage-sankey-panel/CHANGELOG.md
  public/app/plugins/panel/netsage-sankey-panel/LICENSE
  public/app/plugins/panel/netsage-sankey-panel/MANIFEST.txt
  public/app/plugins/panel/netsage-sankey-panel/README.md
  public/app/plugins/panel/netsage-sankey-panel/img/logo.svg
  public/app/plugins/panel/netsage-sankey-panel/img/sankey2.png
  public/app/plugins/panel/netsage-sankey-panel/img/sankey3.png
  public/app/plugins/panel/netsage-sankey-panel/module.js
  public/app/plugins/panel/netsage-sankey-panel/module.js.LICENSE.txt
  public/app/plugins/panel/netsage-sankey-panel/module.js.map
  public/app/plugins/panel/netsage-sankey-panel/plugin.json
Labels: size/XXL

#38 New sankey chart, styled from designs
  .eslintignore
  public/app/features/plugins/built_in_plugins.ts
  public/app/plugins/panel/img/logo.svg
  public/app/plugins/panel/netsage-sankey-panel/CHANGELOG.md
  public/app/plugins/panel/netsage-sankey-panel/LICENSE
  public/app/plugins/panel/netsage-sankey-panel/MANIFEST.txt
  public/app/plugins/panel/netsage-sankey-panel/README.md
  public/app/plugins/panel/netsage-sankey-panel/img/logo.svg
  public/app/plugins/panel/netsage-sankey-panel/img/sankey2.png
  public/app/plugins/panel/netsage-sankey-panel/img/sankey3.png
  public/app/plugins/panel/netsage-sankey-panel/module.js
  public/app/plugins/panel/netsage-sankey-panel/module.js.map
  public/app/plugins/panel/netsage-sankey-panel/plugin.json
  public/app/plugins/panel/sankey-panel-0.5.0/.gitignore
  public/app/plugins/panel/sankey-panel-0.5.0/.prettierignore
  public/app/plugins/panel/sankey-panel-0.5.0/LICENSE
  public/app/plugins/panel/sankey-panel-0.5.0/README.md
  public/app/plugins/panel/sankey-panel-0.5.0/img/logo.svg
  public/app/plugins/panel/sankey-panel-0.5.0/module.js
  public/app/plugins/panel/sankey-panel-0.5.0/module.js.LICENSE.txt
  public/app/plugins/panel/sankey-panel-0.5.0/module.js.map
  public/app/plugins/panel/sankey-panel-0.5.0/plugin.json
Labels: size/XXL

#37 loading hidden variables
  public/app/core/reducers/fn-slice.ts
  public/app/fn-app/create-mfe.ts
  public/app/fn-app/filter-constants/constants.ts
  public/app/fn-app/filter-constants/index.ts
  public/app/fn-app/filter-constants/types.ts
  public/app/fn-app/fn-dashboard-page/fn-dashboard.tsx
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
  public/app/fn-app/utils.tsx
Labels: size/XL

#40 FN Add transform function in sankey panel
  public/app/plugins/panel/sankey-panel-0.5.0/module.js
  public/app/plugins/panel/sankey-panel-0.5.0/module.js.map
  public/app/plugins/panel/sankey-panel-0.5.0/plugin.json
Labels: size/S

#41 Update Sankey styling
  public/app/plugins/panel/sankey-panel-0.5.0/module.js
  public/app/plugins/panel/sankey-panel-0.5.0/module.js.map
  public/app/plugins/panel/sankey-panel-0.5.0/plugin.json
Labels: size/S
