Repository fluxninja/grafana, pull requests merged in 2023-01, with the labels that each got.

#42 Time range selector changes
  packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerContent.tsx
  packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerFooter.tsx
  packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimeRangeForm.tsx
  packages/grafana-ui/src/components/DateTimePickers/TimeZonePicker/TimeZoneDescription.tsx
Labels: size/M

#44 7829 Read hiddenVariables, mode, FNDashboard from grfana's state
  public/app/core/reducers/fn-slice.ts
  public/app/features/dashboard/components/SubMenu/SubMenu.tsx
  public/app/features/dashboard/components/SubMenu/SubMenuItems.tsx
  public/app/features/dashboard/containers/DashboardPage.tsx
  public/app/fn-app/create-mfe.ts
  public/app/fn-app/fn-dashboard-page/fn-dashboard.tsx
  public/app/fn-app/fn-dashboard-page/render-fn-dashboard.tsx
  public/app/fn-app/types.ts
Labels: bug, size/L

#45 Add tool versions
  .tool-versions
Labels: size/XS

#46 Added support for updating nightly environment
  .circleci/config.yml
Labels: size/S
